window:
  width: 650
  height: 1000
  resizable: true
  fixed_size: false
  floating: true
layout:
  content_margin: 20
  section_spacing: 24
  element_spacing: 12
  card_padding: 12
swatches:
  count: 8
  width: 60
  height: 40
  spacing: 6
  label_spacing: 2
preview:
  live_preview_enabled: true
theme:
  use_system_theme: true
  custom_theme: Adwaita
app:
  first_run: false
