--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zeus/Pictures/wallpapers/Photo by SpaceX.jpg"

-- Special
background="#0c141d"
foreground="#c2c4c6"
cursor="#c2c4c6"

-- Colors
color0="#0c141d"
color1="#857B2D"
color2="#8A7767"
color3="#958F38"
color4="#9F8A77"
color5="#738484"
color6="#AF9985"
color7="#c2c4c6"
color8="#5c6570"
color9="#857B2D"
color10="#8A7767"
color11="#958F38"
color12="#9F8A77"
color13="#738484"
color14="#AF9985"
color15="#c2c4c6"
