[colors.primary]
background = "#0c141d"
foreground = "#c2c4c6"

[colors.cursor]
text = "#0c141d"
cursor = "#c2c4c6"

[colors.vi_mode_cursor]
text = "#0c141d"
cursor = "#c2c4c6"

[colors.search.matches]
foreground = "#0c141d"
background = "#c2c4c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5c6570"
background = "#c2c4c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0c141d"
red = "#857B2D"
green = "#8A7767"
yellow = "#958F38"
blue = "#9F8A77"
magenta = "#738484"
cyan = "#AF9985"
white = "#c2c4c6"

[colors.bright]
black = "#5c6570"
red = "#857B2D"
green = "#8A7767"
yellow = "#958F38"
blue = "#9F8A77"
magenta = "#738484"
cyan = "#AF9985"
white = "#c2c4c6"

[colors.dim]
black = "#c2c4c6"
red = "#857B2D"
green = "#738484"
yellow = "#958F38"
blue = "#9F8A77"
magenta = "#8A7767"
cyan = "#AF9985"
white = "#5c6570"

