[colors]
background = '#0c141d8e'
black = '#0c141d'
blue = '#857B2D'
cursor = '#c2c4c6'
cyan = '#8A7767'
foreground = '#c2c4c6'
green = '#958F38'
magenta = '#9F8A77'
red = '#738484'
tabs = '#c2c4c6'
tabs-active = '#AF9985'
white = '#c2c4c6'
yellow = '#c2c4c6'
dim-black = '#0c141d8e'
dim-blue = '#857B2D8e'
dim-cyan = '#8A77678e'
dim-foreground = '#c2c4c68e'
dim-green = '#958F388e'
dim-magenta = '#9F8A778e'
dim-red = '#7384848e'
dim-white = '#AF99858e'
dim-yellow = '#c2c4c68e'
light-black = '#857B2D'
light-blue = '#8A7767'
light-cyan = '#958F38'
light-foreground = '#9F8A77'
light-green = '#738484'
light-magenta = '#AF9985'
light-red = '#c2c4c6'
light-white = '#857B2D'
light-yellow = '#8A7767'
